fix: don't create containers

diff --git a/.github/workflows/retag-containers-after-push.yml b/.github/workflows/retag-containers-after-push.yml
--- a/.github/workflows/retag-containers-after-push.yml
+++ b/.github/workflows/retag-containers-after-push.yml
@@ -34,128 +34,132 @@ jobs:
     name: Retag the containers
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
-        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
-        with:
-          fetch-depth: 2
-
-      - name: Find out if current commit is a merge
-        shell: bash
+      - name: Not a real step
         run: |
-          EXIT_CODE=0
-          # a commit always has a parent, but if it has 2, the commit is a merge
-          # so lets see if we have one
-          # since we're listening to the push event we have to do this manually
-          PARENT2=$(git rev-parse "HEAD^2" --quiet 2>/dev/null) || EXIT_CODE=$?
+          echo "Just here to not have to restructure too much"
 
-          if [ ${EXIT_CODE} -eq 0 ]
-          then
-            echo "The head of the incoming PR is ${PARENT2}"
-            echo "INCOMING_PR_HEAD_COMMIT=${PARENT2}" >> ${GITHUB_ENV}
+      # - name: Checkout
+      #   uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
+      #   with:
+      #     fetch-depth: 2
 
-          else
-            echo "The incoming push isn't a merge, ergo it's not a PR"
-          fi
+      # - name: Find out if current commit is a merge
+      #   shell: bash
+      #   run: |
+      #     EXIT_CODE=0
+      #     # a commit always has a parent, but if it has 2, the commit is a merge
+      #     # so lets see if we have one
+      #     # since we're listening to the push event we have to do this manually
+      #     PARENT2=$(git rev-parse "HEAD^2" --quiet 2>/dev/null) || EXIT_CODE=$?
 
-      - name: Setup Node.js
-        uses: actions/setup-node@04c56d2f954f1e4c69436aa54cfef261a018f458
-        with:
-          node-version-file: ".nvmrc"
-          cache: "npm"
-          cache-dependency-path: "**/package-lock.json"
+      #     if [ ${EXIT_CODE} -eq 0 ]
+      #     then
+      #       echo "The head of the incoming PR is ${PARENT2}"
+      #       echo "INCOMING_PR_HEAD_COMMIT=${PARENT2}" >> ${GITHUB_ENV}
 
-      - name: Install dependencies
-        shell: bash
-        run: |
-          npm ci --ignore-scripts
+      #     else
+      #       echo "The incoming push isn't a merge, ergo it's not a PR"
+      #     fi
 
-      - name: Download crane tar, extract, and add folder to path.
-        uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667
-        with:
-          script: |
-            const tc = require("@actions/tool-cache");
+      # - name: Setup Node.js
+      #   uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
+      #   with:
+      #     node-version: "lts/*"
+      #     cache: "npm"
+      #     cache-dependency-path: "**/package-lock.json"
 
-            const release = await github.rest.repos.getLatestRelease({
-                owner: "google",
-                repo: "go-containerregistry"
-            });
+      # - name: Install dependencies
+      #   shell: bash
+      #   run: |
+      #     npm ci --ignore-scripts
 
-            const asset = release.data.assets.find(asset => {
-                return asset["content_type"] === "application/gzip" && asset.name === "go-containerregistry_Linux_x86_64.tar.gz";
-            });
+      # - name: Download crane tar, extract, and add folder to path.
+      #   uses: actions/github-script@441359b1a30438de65712c2fbca0abe4816fa667
+      #   with:
+      #     script: |
+      #       const tc = require("@actions/tool-cache");
 
-            const urlToCraneTar = asset.browser_download_url
+      #       const release = await github.rest.repos.getLatestRelease({
+      #           owner: "google",
+      #           repo: "go-containerregistry"
+      #       });
 
-            const craneTarPath = await tc.downloadTool(urlToCraneTar);
-            const craneExtractedFolder = await tc.extractTar(craneTarPath, null, ["--extract", "--gzip"]);
+      #       const asset = release.data.assets.find(asset => {
+      #           return asset["content_type"] === "application/gzip" && asset.name === "go-containerregistry_Linux_x86_64.tar.gz";
+      #       });
 
-            core.addPath(craneExtractedFolder);
+      #       const urlToCraneTar = asset.browser_download_url
 
-      - name: Log into registry ${{ env.REGISTRY }}
-        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
-        with:
-          registry: ${{ env.REGISTRY }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
+      #       const craneTarPath = await tc.downloadTool(urlToCraneTar);
+      #       const craneExtractedFolder = await tc.extractTar(craneTarPath, null, ["--extract", "--gzip"]);
 
-      - name: Set full image name
-        shell: bash
-        run: |
-          echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}
+      #       core.addPath(craneExtractedFolder);
 
-      - name: Find all tags for ${{ env.FULL_IMAGE_NAME }}
-        shell: bash
-        run: |
-          crane ls ${FULL_IMAGE_NAME} >> existing_tags
+      # - name: Log into registry ${{ env.REGISTRY }}
+      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
+      #   with:
+      #     registry: ${{ env.REGISTRY }}
+      #     username: ${{ github.actor }}
+      #     password: ${{ secrets.GITHUB_TOKEN }}
 
-          echo "These are the existing tags on ${FULL_IMAGE_NAME}:"
-          cat existing_tags
+      # - name: Set full image name
+      #   shell: bash
+      #   run: |
+      #     echo "FULL_IMAGE_NAME=${REGISTRY,,}/${IMAGE_NAME,,}" >> ${GITHUB_ENV}
 
-      - name: Check if the incoming PR has a Docker container, which will be our old tag, if not, or if it's just a push, find the appropriate old tag
-        env:
-          PR_TAG: "pr-${{ github.event.before }}-${{ env.INCOMING_PR_HEAD_COMMIT }}"
-        shell: bash
-        run: |
-          # search for the tag, there can only be zero or one match
-          # we need the || true because otherwise grep returns exit code 1 and github actions then dies
-          pr_tag_found=$(cat existing_tags | grep -c "^${PR_TAG}\$") || true
+      # - name: Find all tags for ${{ env.FULL_IMAGE_NAME }}
+      #   shell: bash
+      #   run: |
+      #     crane ls ${FULL_IMAGE_NAME} >> existing_tags
 
-          if [ $pr_tag_found -eq 1 ]
-          then
-            echo "Incoming PR produced a Docker image"
+      #     echo "These are the existing tags on ${FULL_IMAGE_NAME}:"
+      #     cat existing_tags
 
-            echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}
-            echo "SUFFIX=actual" >> ${GITHUB_ENV}
-          else
-            # If we don't have an old tag, then the incoming PR didn't produce a container.
-            # In which case we're going to find the container referenced to the base commit, and add our current sha as a tag to it
+      # - name: Check if the incoming PR has a Docker container, which will be our old tag, if not, or if it's just a push, find the appropriate old tag
+      #   env:
+      #     PR_TAG: "pr-${{ github.event.before }}-${{ env.INCOMING_PR_HEAD_COMMIT }}"
+      #   shell: bash
+      #   run: |
+      #     # search for the tag, there can only be zero or one match
+      #     # we need the || true because otherwise grep returns exit code 1 and github actions then dies
+      #     pr_tag_found=$(cat existing_tags | grep -c "^${PR_TAG}\$") || true
 
-            echo "Incoming PR produced nothing, or there was just a push to main"
+      #     if [ $pr_tag_found -eq 1 ]
+      #     then
+      #       echo "Incoming PR produced a Docker image"
 
-            # so we find the last commit that github processed before this one
-            # which will have gone through the same retagging process
-            # and use that sha as our key to find the Docker container related to that commit
-            old_tag=$(cat existing_tags | grep "^sha-${{ github.event.before }}-.*\$") # .* is actual or retag
+      #       echo "OLD_TAG=${PR_TAG}" >> ${GITHUB_ENV}
+      #       echo "SUFFIX=actual" >> ${GITHUB_ENV}
+      #     else
+      #       # If we don't have an old tag, then the incoming PR didn't produce a container.
+      #       # In which case we're going to find the container referenced to the base commit, and add our current sha as a tag to it
 
-            echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}
-            echo "SUFFIX=retag" >> ${GITHUB_ENV}
-          fi
+      #       echo "Incoming PR produced nothing, or there was just a push to main"
 
-      - name: Set the new TAGs
-        id: meta
-        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
-        with:
-          images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
-          flavor: |
-            latest=false
-          tags: |
-            type=edge,branch=main
-            type=sha,format=long,prefix=sha-,suffix=-${{ env.SUFFIX }}
+      #       # so we find the last commit that github processed before this one
+      #       # which will have gone through the same retagging process
+      #       # and use that sha as our key to find the Docker container related to that commit
+      #       old_tag=$(cat existing_tags | grep "^sha-${{ github.event.before }}-.*\$") # .* is actual or retag
 
-      - name: Actually re-tag the container
-        shell: bash
-        run: |
-          echo "${{ steps.meta.outputs.tags }}" | while read new_tag
-          do
-            crane cp "${FULL_IMAGE_NAME}:${OLD_TAG}" ${new_tag}
-          done
+      #       echo "OLD_TAG=${old_tag}" >> ${GITHUB_ENV}
+      #       echo "SUFFIX=retag" >> ${GITHUB_ENV}
+      #     fi
+
+      # - name: Set the new TAGs
+      #   id: meta
+      #   uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
+      #   with:
+      #     images: "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}"
+      #     flavor: |
+      #       latest=false
+      #     tags: |
+      #       type=edge,branch=main
+      #       type=sha,format=long,prefix=sha-,suffix=-${{ env.SUFFIX }}
+
+      # - name: Actually re-tag the container
+      #   shell: bash
+      #   run: |
+      #     echo "${{ steps.meta.outputs.tags }}" | while read new_tag
+      #     do
+      #       crane cp "${FULL_IMAGE_NAME}:${OLD_TAG}" ${new_tag}
+      #     done
